[workspace]
authors = ["Marco A. Lopez-Sanchez <marcoalopez@protonmail.com>"]
channels = ["conda-forge"]
name = "pyrockwave"
platforms = ["win-64", "linux-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "<3.14"
numpy = ">=2.5.0,<3"
scipy = ">=1.18.0,<2"
pandas = ">=3.0.3,<4"
matplotlib = ">=3.11.0,<4"
jupyterlab = ">=4.6.0,<5"
